---
apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: $PREFIX-tsb-gateway
  namespace: $PREFIX-workshop-app
spec:
  kubeSpec:
    service:
      type: LoadBalancer
      annotations:
        "external-dns.alpha.kubernetes.io/hostname": "demo-app.cloud-b-01.$PREFIX.workshop.cx.tetrate.info."
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend
  namespace: $PREFIX-workshop-app
spec:
  secretName: frontend-certs
  issuerRef:
    name: letsencrypt-dns-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - demo-app.cloud-b-01.$PREFIX.workshop.cx.tetrate.info