---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  displayName: secure-default
  name: secure-default
  organization: visa
  tenant: $PREFIX-workshop
  workspace: marketdata
spec:
  defaultSecuritySetting:
    authenticationSettings:
      trafficMode: REQUIRED
  displayName: secure-default