---
apiVersion: v1
kind: Namespace
metadata:
  name: $PREFIX-tier1
---
apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: $PREFIX-tier1-gateway
  namespace: $PREFIX-tier1
spec:
  kubeSpec:
    service:
      type: LoadBalancer
      # This will be used to demo Tier1 w/ our sample app
      annotations:
        "external-dns.alpha.kubernetes.io/hostname": "demo-app.$PREFIX.workshop.cx.tetrate.info."
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend
  namespace: $PREFIX-tier1
spec:
  secretName: frontend-certs
  issuerRef:
    name: letsencrypt-dns-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - demo-app.$PREFIX.workshop.cx.tetrate.info