---
apiVersion: gateway.tsb.tetrate.io/v2
kind: EgressGateway
metadata:
  tenant: $PREFIX-workshop
  organization: visa
  workspace: workshop-app
  group: egress
  name: egress-gateway
spec:
  workloadSelector:
    namespace: $PREFIX-security 
    labels:
      app: $PREFIX-cluster-egress
  authorization:
  - to:
    - "*.httpbin.org"
    from:
      mode: CUSTOM
      serviceAccounts:
        - $PREFIX-workshop-app/secure-frontend