---
apiVersion: v1
kind: Namespace
metadata:
  name: $PREFIX-quotes
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quotes-vm
  namespace: $PREFIX-quotes