---
apiVersion: v1
kind: Service
metadata:
  name: quotes
  namespace: $PREFIX-quotes
  labels:
    app: quotes
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: quotes
  type: ClusterIP
---
apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: $PREFIX-tsb-quotes-gateway
  namespace: $PREFIX-quotes
spec:
  kubeSpec:
    service:
      type: LoadBalancer
